### PR TITLE
Add annotations

### PR DESCRIPTION
**Pull request by retrodaredevil**
This PR allows you to query GraphQL for annotations.

The editor is a lot different from the one for normal queries because its harder to give Grafana a PureComponent, so I decided to go a simpler route and copy how most of the other annotation data sources are using `annotations.editor.html`.

Two methods were added to the DataSource class which splits up some of the logic for creating a query and for parsing docs. The `getDocs()` method also throws more useful errors if you don't get the data you expect back.

Both of those new methods are utilized in `annotationQuery()`. The annotation logic is pretty simple and it uses a pretty similar format to regular querying. It can have completely custom title, text and tags data that can be substituted with field's values like `$field_<field name>`. This is explained in the updated readme.

Let me know if you want me to change anything or if this isn't what you had in mind for annotations.

### CODE REVIEW

**Comment by retzkek** [comment]
Thanks @retrodaredevil, this is great! I hadn't considered what it would take to support annotations, but I see many ways we can use this, so I really appreciate it!

One thing I would like to see is support for template variables in the annotations query. I think it may be as simple as calling `this.templateSrv.replace()` even if `scopedVars` is undefined or null at https://github.com/retrodaredevil/graphql-datasource/blob/master/src/DataSource.ts#L76

**Comment by retrodaredevil** [comment]
Yep, I believe that was pretty simple. All I had to do was remove the if statement. I will say I haven't tested template variables at all, but I can confirm this change doesn't throw errors or anything.

**Comment by retzkek** [comment]
I tested with a variable, it worked. After this I think I'll look at cutting a 1.0 release and opening a PR to add it to the plugin repository. Thanks again for the contributions!

**Comment by retzkek** [comment]
Sorry I missed the edit. I don't think that's necessary, nor do other data sources do that AFAIK.

**Pull request merged**
