### PR TITLE
automatically detect dates in strings

### PR DESCRIPTION
**Pull request by michaelneale**
I like the ability to set `Time` as an alias, however I also like that given that grafana is heavily flavoured towards the timeseries database, that if there is an RFC3339 (json standard) or ISO8601 (a superset of that) string present, then it should automatically set the data type to date (to avoid mistaking it for a string and messing up sorting/grafing). 

What do you think of this @retzkek ?

### CODE REVIEW

**Comment by retzkek** [comment]
There's some discussion on this in #25, but that's more focused on how to set the time abscissa. I like the idea of trying to detect time fields for the data frame, but that is a deep rabbit hole (alas, if only JSON had types!). Your regex looks like a fine first-order approximation, but will notably only catch UTC timestamps. And maybe that's good enough, falling back to a string doesn't leave us any worse than now. Maybe `moment.js` or `@grafana/data` has something we can leverage instead of writing our own?

**Comment by retrodaredevil** [comment]
What is the benefit of making the FieldType time? I know it has to be done for the actual timestamp, but is there a use case for having multiple fields be recognized as a date by Grafana? I'm just curious to what this is used for.

**Comment by michaelneale** [comment]
@retrodaredevil the second benefit is that it sets the type correctly, so if you had multiple times, it would sort correctly in a table (for example). I expect there are other ones for having the type.. but mostly that. 

@retzkek yeah, it is a bit of a rabbit hole. I limited it to UTC to narrow it (as that seems to be the convention). 
I didn't find anything in `@grafana/data` for this. moment does have some helper methods to validate: `moment("2011-10-10T14:48:00", moment.ISO_8601).isValid()` - but it is exposed from grafana, so it would need to be a new dependency right? If we were to do this, would need to limit it to that format, as any number is also a valid date (which we don't want). 

https://stackoverflow.com/questions/10286204/the-right-json-date-format
https://tools.ietf.org/html/rfc3339

On another note, I love that this plugin is so active. I am new to graphql and grafana but things just seem to work nicely.

**Comment by retzkek** [comment]
> but it is exposed from grafana, so it would need to be a new dependency right? 

Just a dev dependency maybe, since Grafana does expose moment, there's even a function to convert to it: https://grafana.com/docs/grafana/latest/packages_api/data/datetimeasmoment/

> On another note, I love that this plugin is so active. I am new to graphql and grafana but things just seem to work nicely.

It's really thanks to people like you and @retrodaredevil for getting involved, the Grafana community is great!

**Comment by michaelneale** [comment]
@retzkek ah - I should try a dev dependency, that would make sense. 

I did try that other one, but it doesn't work, as if the field happens to be a number, it will successfully convert to a date -> moment (we don't get a chance to check for ISO format). But if a dev dependency works, that seems more solid. I will try that out today if I can and update it here if it works.

**Comment by michaelneale** [comment]
@retzkek momentjs seems to work nicely - no regex. I added some more test scenarios and made sure it covered the case where there is no sub second values (not uncommon).

**Comment by michaelneale** [comment]
@retzkek @retrodaredevil had any more thoughts on this?

**Comment by retrodaredevil** [comment]
I think that this could be something that could get merged. Another possible way that this could be done is being able to say what types from a GraphQL schema correspond to date types, but I think we're a little ways away from actually doing something like that.

Since I don't think this breaks existing queries, I don't see much harm in this enhancement. It's not perfect, but I think it would work nicely.

**Comment by retzkek** [comment]
Sorry I haven't had much time to look at this. @michaelneale could you rebase this onto master, that should pick up the updated CI config.

> Another possible way that this could be done is being able to say what types from a GraphQL schema correspond to date types, but I think we're a little ways away from actually doing something like that.

Wouldn't it be great if GraphQL included a time type? They kinda dropped the ball there unfortunately, leaving users and libraries to come up with their own way for handling date and times, meaning everyone has their own way of doing it.

**Comment by michaelneale** [comment]
@retzkek yeah - a shame about graphql, but I guess they are limited by json which doesn't have an explicit separate date format (it does mention to use that ISO format from what I can tell). 

I have updated this with master, and also switched to using the built in dateTime wrapper as recommended here: https://github.com/grafana/grafana/issues/22950 

I also was trying out github actions as simpler than circle here: https://github.com/fifemon/graphql-datasource/pull/27 (but unrelated).

**Comment by retzkek** [comment]
Looks good, thanks!

**Pull request merged**
