### PR TITLE
Monospace

### PR DESCRIPTION
**Pull request by michaelneale**
make the query editor easier to see with monospace

### CODE REVIEW

**Comment by michaelneale** [comment]
@retzkek from https://github.com/fifemon/graphql-datasource/pull/22 - updated too

**Comment by retzkek** [comment]
Perusing the new UI docs I found there's a `QueryField` component, which is probably what we really should be using: https://developers.grafana.com/ui/latest/index.html?path=/docs/data-source-queryfield--basic

I did a quick comparison, in addition to a monospace font it also resizes to fit the query, and will allow us to add auto-complete and syntax highlighting (#11). 
image


Want to look at using that instead? Here's the code I used, but I haven't looked over all the parameters so it may be missing some things we need:

```typescript
        <QueryField
          query={queryText || ''}
          onChange={this.onChangeQuery}
          portalOrigin="graphQL"
        />
```

where `onChangeQuery()` is pretty similar to the existing `onQueryTextChange()`:

```typescript
  onChangeQuery = (value: string, override?: boolean) => {
    const { onChange, query } = this.props;
    if (onChange) {
      onChange({ ...query, queryText: value });
    }
  };
```

**Comment by michaelneale** [comment]
@retzkek thanks for the tip - that seems good, see change, seems to work well. I like the idea of allowing content assist.. this could be really really handy, but this opens the way for it.

**Comment by retzkek** [comment]
LGTM. Thanks for the contribution!

**Pull request merged**
