### PR TITLE
make isRFC3339_ISO6801() require string argument

### PR DESCRIPTION
**Pull request by retzkek**
It doesn't make sense to accept `any`, and can cause issues like #32. I just coerce the field to a `String()` in the caller, which I believe should degrade gracefully (and the tests agree).

### CODE REVIEW

**Comment by retzkek** [comment]
@ricochet1k or @carvid could you test this and verify it fixes your issue, before I merge and cut a release?
You can install it directly from github:

```
cd $GF_PATHS_PLUGINS # or maybe $GF_PLUGIN_DIR. Default is /var/lib/grafana/plugins
git clone https://github.com/retzkek/graphql-datasource.git -b iso-require-string
```
then restart grafana.

**Comment by carvid** [comment]
> @ricochet1k or @carvid could you test this and verify it fixes your issue, before I merge and cut a release?
> You can install it directly from github:
> 
> ```
> cd $GF_PATHS_PLUGINS # or maybe $GF_PLUGIN_DIR. Default is /var/lib/grafana/plugins
> git clone https://github.com/retzkek/graphql-datasource.git -b iso-require-string
> ```
> 
> then restart grafana.

@retzkek It worked for me.

**Comment by carvid** [comment]
Hi @retzkek. Any chance to get this fix released soon?. We started to hit the error in several new queries 😬 .

**Comment by retzkek** [comment]
@carvid thanks for testing. Sure I'll cut a release right now. Note that it will take several days to get the update into the Grafana repo.

**Pull request merged**
