### PR TITLE
Multiple data paths and 'data' not necessary

### LINKED ISSUE #7: Should the first 'data' in the data path be optional?
Right now when specifying a data path, you always use `data.<something>`. Take this query:

```
query {
    data:submissions(user:"$user", from:"$timeFrom", to:"$timeTo"){
        Time:submitTime
        idle running completed
    }
}
```
The data path is `data.data`. Obviously the second data makes sense, but does the first "data" ever change? Unless there's a reason that I'm unaware of, making the data path just `data` for the above query makes more sense.

If you agree with this, we could probably phase out the first "data" in the data path and make it optional. This could prove to be difficult (for instance does "data.data" become "data.data.data" internally or just stay as "data.data"). But a data path like "submissions" could be internally converted to "data.submissions".

Also, I plan to submit a PR later for multiple data paths in the same query. I probably won't change this in that PR.

### PR DESCRIPTION
**Pull request by retrodaredevil**
This PR allows you to have multiple data paths. This is useful if you are querying multiple servers and don't want to have to create a bunch of queries that are very similar, you can just put multiple queries into one, like GraphQL was made for.

This also removes the first 'data' from the data path. This means that this is NOT backwards compatible with past versions of this datasource, but is a very simple change (just remove the first 'data' from all your query's data paths). I was gonna do this in a different PR, but I got lazy and the changes I made are pretty close together.

Instead of passing the results object into `getDocs()`, the data object is passed into `getDocs()` which (might) have the `data` and `errors` fields.

The reason it looks like there are so many changes is because everything had to be indented once when I added the for loop, so really there aren't that many changes.

Closes #7

### CODE REVIEW

**Comment by retzkek** [comment]
Looks good, worked in tests. Multiple data paths is great, it's simpler than trying to merge multiple targets like I was thinking. However, I think we could improve the UI a bit to have each data path have its own field, with buttons to add or remove them, as is done in other data sources, like in this mockup:

image

I'm also fine merging this PR as-is, cutting a new release, and making that a new issue, since it may make sense to do that as part of a larger UI makeover, e.g. having the datapath editor work like the graphite editor, where each level is a drop-down based on the query.

**Comment by retrodaredevil** [comment]
I definitely like the idea of adding that. I'm not familiar with how to do this, but I'll look into it for regular queries. However, for annotation queries, I think they'll be much different unless the UI for regular querying is refactored.

When I added annotations, I wanted to try to use a similar layout to how the UI for regular queries were, but there were no good examples of how to do that and all the examples pushed me to implement the `annotations.editor.html` file. 

It might be worth refactoring the UI for annotations and regular queries to use a more similar query editor. I'll try it out and see how it goes, but I have very little experience with this UI stuff.

**Comment by retzkek** [comment]
> I'm not familiar with how to do this, but I'll look into it for regular queries.
Awesome! The buttons I used in the mockup were from the Elasticsearch data source metrics settings, if that helps.

> However, for annotation queries, I think they'll be much different unless the UI for regular querying is refactored.

Annotations are definitely their own beast, other datasources have a pretty spartan editor as well. I wouldn't be surprised if the Grafana devs have some plans there as part of the React refactor.

**Comment by retrodaredevil** [comment]
I probably won't get to this for a day or two. I tried working on this earlier by looking Graphite, InfluxDB and Flux examples.

It looks like it's possible to try and create a component that can be inlined in the regular query as well as the annotation query.

If you decide to merge this in, I can create another pull request when I get around to trying this again. Whichever you want.

**Comment by retzkek** [comment]
Yeah, I'll merge this in and cut a release, since it is functionally sound and includes the data path change. Thanks again for the contribution!

**Pull request merged**
