### PR TITLE
support GraphQL subscriptions

### LINKED ISSUE #57: Support GraphQL subscriptions
**Is your feature request related to a problem? Please describe.**
GraphQL allows for [subscriptions](https://www.apollographql.com/docs/react/data/subscriptions/) where data is pushed to the client rather than pulled by the client itself. This happens live via websockets which Grafana also [supports](https://grafana.com/docs/grafana/latest/developers/plugins/build-a-streaming-data-source-plugin/).
I'm currently coding a live vehicle dashboard where data is fetched via GraphQL. A vehicle may drive or be stationary at any time so polling via GraphQL may just create unnecessary network traffic and load. With pushing via websockets traffic would only occur when a change in the data source happens.

**Describe the solution you'd like**
Simply changing any supported query from `query` to `subscription` should automatically open a websocket connection to the GraphQL endpoint. When one of the requested query value changes, the change should be immediately reflected on the dashboard without polling.

**Describe alternatives you've considered**
Grafana polling. Works but it always fetches data even when no new data is available at the source.

### PR DESCRIPTION
**Pull request by SydoxX**
Closes #57

### CODE REVIEW

**Comment by SydoxX** [comment]
I did not find any documentation if Grafana officially supports proxying websockets. For now only the `Browser` option supports websockets and therefor subscriptions.

**Comment by retzkek** [comment]
This looks really nice, thanks! Subscriptions were on my "nice to have" long-term roadmap, I really appreciate you taking this on. Give me a few days to review all these changes. 

Can you recommend a datasource to test this with? Otherwise I'll just implement subscriptions in the [test datasource](https://github.com/fifemon/graphql-test-source) (which should support it regardless for demonstration).

**Comment by SydoxX** [comment]
Unfortunately I tested it locally on an internal Hasura server.

**Comment by retzkek** [comment]
@SydoxX I'm really sorry it took so long for me to look at this. I finally added subscriptions to the test datasource, and have a couple immediate comments:

1. I don't think it's a safe assumption that the subscription websockets endpoint is the same as the query endpoint. It's probably best to add a new configuration option, which could default to the same endpoint.
2. Grafana does appear to proxy websockets, at least when looking at "live" Loki logs in Explore.

**Comment by SydoxX** [comment]
> @SydoxX I'm really sorry it took so long for me to look at this. I finally added subscriptions to the test datasource, and have a couple immediate comments:
> 
>     1. I don't think it's a safe assumption that the subscription websockets endpoint is the same as the query endpoint. It's probably best to add a new configuration option, which could default to the same endpoint.
> 
>     2. Grafana does appear to proxy websockets, at least when looking at "live" Loki logs in Explore.

1. Indeed, I'll add another config option.
2. Thanks for the heads-up, I'll see if I can get proxied websockets working.

**Comment by SydoxX** [comment]
Added text field to enter websocket url and also added some info boxes about GraphQL subscriptions.

**Comment by SydoxX** [comment]
I updated grafana in the package.json to version 8.1.4 but unfortunately this results in an endless loop while executing `npm install`. But I suspect this is a problem on my side.

**Pull request closed without merging**
